AllCops:
  NewCops: enable
  Exclude:
    - rslp.gemspec
    - Gemfile
    - Rakefile

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/BlockComments:
  Enabled: false
